services:
  api-integ-pagseguro-mysql:
    image: mysql:8.0.34
    container_name: api-integ-pagseguro-mysql
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - "./api-integ-pagseguro/mysql/data:/var/lib/mysql"